# Generated by Django 4.1.5 on 2023-02-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_orders_payment_completed_orders_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_method',
        ),
    ]
